version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
        -run: npm install
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
